export const Sales = [
	{
		instagram: '@açaínograu',
		name: 'Açaí no Grau - Fátima',
		description: '10% de desconto.',
		imageUrl: '/profile/acai.jpg',
	},
	{
		instagram: '@arenasaqualine',
		name: 'Arenas Aqualine',
		description: null, 
		imageUrl: '/profile/aqualine.jpg',
	},
	{
		instagram: '@ctaarena',
		name: 'Arena CTA',
		description: '15% de desconto no valor da hora dos campos society.',
		imageUrl: '/profile/arena.jpg',
	},
	{ 
		instagram: '@maisbrazilianburger',
		name: '+Brazilian Burger',
		description: '15% de desconto nos sanduíches e combos (não cumulativo com outras promoções, não válido para plataformas de delivery).',
		imageUrl: '/profile/burger.jpg',
	},
	{
		instagram: '@cavalcantiea',
		name: 'Cavalcanti Estética Automotiva',
		description: '10% de desconto.',
		imageUrl: '/profile/cavalcanti.jpg',
	},
	{
		instagram: '@cakes_da_gleidy',
		name: 'Cakes da Gleidy',
		description: '10% de desconto nos bolos.',
		imageUrl: '/profile/cakes.jpg',
	},
	{
		instagram: '@calorsunglasses',
		name: 'Calor Sunglasses',
		description: '15% de desconto.',
		imageUrl: '/profile/calor.jpg',
	},
	{
		instagram: '@odonto.fellice',
		name: 'Clínica Odontológica Fellice',
		description: '20% de desconto.',
		imageUrl: '/profile/felice.jpg',
	},
	{
		instagram: '@clubedovoleithe',
		name: 'Clube do Vôlei',
		description: null,
		imageUrl: '/profile/clubedovolei.jpg',
	},
	{
		instagram: '@comapi',
		name: 'Comapi',
		description: null,
		imageUrl: '/profile/comapi.jpg',
	},
	{
		instagram: '@doctorstorethe',
		name: 'Doctor Store',
		description: '10% de desconto.',
		imageUrl: '/profile/doctor.jpg',
	},
	{
		instagram: '@fatiopizzaria',
		name: 'Fatiô Pizzaria',
		description: null,
		imageUrl: '/profile/pizza.jpg',
	},
	{
		instagram: '@papelariafelina',
		name: 'Felina Papelaria',
		description: '15% de desconto.',
		imageUrl: '/profile/felina.jpg',
	},
	{
		instagram: '@grelhadosriverside',
		name: 'Grelhado\'s\ Self-Service',
		description: '10% de desconto ou prato estudantil por R$15 (prato estudantil: 1 prot e até 500g).',
		imageUrl: '/profile/grelhados.jpg',
	},
	{
		instagram: '@icecreamrollbr.riopoty',
		name: 'Ice Cream Roll Rio Poty',
		description: null,
		imageUrl: '/profile/roll.jpg',
	},
	{
		instagram: '@lustore11',
		name: 'Lu Store',
		description: '25% de desconto em qualquer produto.',
		imageUrl: '/profile/lu.jpg',
	},
	{
		instagram: '@medoutor',
		name: 'Medoutor',
		description: '10% de desconto no kit sutura.',
		imageUrl: '/profile/medoutor.jpg',
	},
	{
		instagram: '@oxentheburger',
		name: 'Oxenthe Burger',
		description: '15% de desconto nos hambúrgueres.', 
		imageUrl: '/profile/oxenthe.jpg',
	},
	{
		instagram: '@pizzaria_oheroi',
		name: 'Pizzaria O Herói',
		description: '13% de desconto.',
		imageUrl: '/profile/heroi.jpg',
	},
	{
		instagram: '@rcdoces__',
		name: 'RCdoces',
		description: '10% de desconto na palha italiana.',
		imageUrl: '/profile/recdoces.jpg',
	},
	{
		instagram: '@revitabarbershop',
		name: 'Revitá Barber Shop',
		description: 'Cortes únicos (cabelo ou barba) por R$30, cabelo e barba por R$55, 10% de desconto nos demais serviços de barbearia. Além de 15% para primeira vez (quem ainda não tem cadastro), 10% para clientes contínuos (demais visitas) no salão (descontos não cumulativos)', 
		imageUrl: '/profile/revita.jpg',
	},
	{
		instagram: '@sem_insta',
		name: 'Salvatore Barbearias',
		description: null, 
		imageUrl: '/profile/cavalcanti.jpg',
	},
	{
		instagram: '@scrub.doctor',
		name: 'Scrub Doctor',
		description: '10% de desconto em qualquer produto e entrega grátis (apenas no primeiro pedido).',
		imageUrl: '/profile/scrub.jpg',
	},
	{
		instagram: '@scrub.on',
		name: 'Scrub On',
		description: '15% de desconto.',
		imageUrl: '/profile/scrubon.jpg',
	},
	{
		instagram: '@dtortugo',
		name: 'Tortugo',
		description: '10% de desconto de terça a quinta.',
		imageUrl: '/profile/tortugo.jpg',
	},
	{
		instagram: '@eliaslpo',
		name: 'Treinador Elias Fernandes',
		description: '20% de desconto na preparação física (turmas de até 5 pessoas ganham 25%) às 09h ou às 12h, ou 10% em qualquer outro horário, 50% em eventos.', 
		imageUrl: '/profile/treinador.jpg',
	},
]